CanExplode: true
CanSpawnCreature: true
CanGenerateTree: true
CanExplode: true
CanSetDay: true
CanSetNight: true
CanSpawnCreepers: true
CanDropDiamonds: true
CanTeleportPlayer: true
CanDropBomBow: true
CanDropStickOfFire: true
CanCanDropTelebow: true
CanLaunchPlayer: true
CanSpawnTrident: true

# --- General Control ---
PlaySound: true
LaunchPlayerAmount: 5
TridentSummon: true