name: SurpriseEggs
main: net.ddns.vcccd.Main
version: 1.0.3
api-version: 1.20
commands:
   surpriseeggs:
      description: Get plugin information for suprise Eggs
      usage: /<command>
      permission: supriseeggs.versioninfo
