name: SurpriseEggs
main: net.ddns.vcccd.Main
version: 1.0
api-version: 1.20
commands:
   supriseeggs:
      description: Get plugin information for suprise Eggs
      usage: /<command>
      permission: supriseeggs.versioninfo